[package]
name = "kube"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kube = "0.95.0"
k8s-openapi = { version = "0.23.0", features = ["latest"] }
tokio = { version = "1.0", features = ["full"] }  